<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPc4gi8s\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPc4gi8s/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPc4gi8s.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPc4gi8s\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPc4gi8s\appProdProjectContainer([
    'container.build_hash' => 'Pc4gi8s',
    'container.build_id' => '4b3ca029',
    'container.build_time' => 1604624996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPc4gi8s');
